#!/usr/bin/perl 

my $name = $ARGV[0];
$name = ucfirst($name);
open CONTROLLER, "<controller.template";
my $controller_temp;

while(<CONTROLLER>){
    $controller_temp .= $_;
}
close CONTROLLER;

open MODEL, "<model.template";
my $model_temp;
while(<MODEL>){
    $model_temp .= $_;
}

close MODEL;

$controller_temp =~ s/\<name\>/$name/geis;
$model_temp =~ s/\<name\>/$name/geis;

my $controller_name = lc($name).'controller.php';
my $model_name = lc($name).'.php';

print 'Creating files '.$name."\n";
my $app_root = '../application/';
open CONTROLLER, "+>$app_root".'controllers/'."$controller_name" or warn "$!";
print 'Creating controller page'.$controller_name."\n";
print CONTROLLER $controller_temp;
close CONTROLLER;

open MODEL, "+>$app_root".'models/'."$model_name" or warn "$!";
print 'Creating model page'.$model_name."\n";
print MODEL $model_temp;
close MODEL;

my $view_name = lc($name).'s';
print 'Creating view directory for '.$name."\n";
mkdir $app_root.'views/'.$name;
